#! /bin/sh
# 
# Install in: /etc/init.d/

case "$1" in
	start)
		if [ -f /home/betancur343/Escritorio/start.sh ];
		#if [ -f /home/pi/Desktop/start.sh ];	
		          then
			    echo $"Starting billAccepter daemon..."
					/bin/su betancur343 /home/betancur343/Escritorio/start.sh
					#/bin/su pi /home/pi/Desktop/start.sh
		        fi
		;;
	stop)
		if [ -f /home/betancur343/Escritorio/stop.sh ];
				#if [ -f /home/pi/Desktop/stop.sh ];	
				          then
				echo $"Shutting down billAccepter daemon..."
					/bin/su betancur343 /home/betancur343/Escritorio/stop.sh
					#/bin/su pi /home/pi/Desktop/stop.sh
		        fi
		;;
	*)
		echo $"Only: start | stop"		
		exit 1
		;;
esac
exit 0